### ISSUE TITLE
Dark mode / Auto Dark mode not available

### ISSUE THREAD

**Issue by Pappmann** [VoxelCubes/DeepQt#4]
Hi,
how can i switch to dark mode?

I tried pip version and flatpak version on Fedora, skin stays always in light mode.

Thanks for support

**Comment by VoxelCubes** [comment]
Currently, it'll follow your Qt system theme. If you use gnome, you'll need to set up some way to theme Qt6 applications. If you have other qt5 apps currently working with theming, that's why it doesn't work since this is qt6.
If you take a look at my other project Panel Cleaner (pip or flathub) I've learned how to add proper theming overrides, to bundle breeze light and breeze dark, which can be switched to in the gui.
I plan of massively overhauling deepqt in march with everything I've learned since them from panel cleaner (built in theme overrides, localization support, better error messages) as well as supporting more backends than only deepl.

**Comment by Pappmann** [comment]
> Currently, it'll follow your Qt system theme. If you use gnome, you'll need to set up some way to theme Qt6 applications. If you have other qt5 apps currently working with theming, that's why it doesn't work since this is qt6. If you take a look at my other project Panel Cleaner (pip or flathub) I've learned how to add proper theming overrides, to bundle breeze light and breeze dark, which can be switched to in the gui. I plan of massively overhauling deepqt in march with everything I've learned since them from panel cleaner (built in theme overrides, localization support, better error messages) as well as supporting more backends than only deepl.

Thanks,  tried panel cleaner but without success with pip install. Is there a easy workaround to change the skin to dark local in the code?

**Comment by VoxelCubes** [comment]
It isn't hard to hardcode a palette, but I won't help you with that. I'll handle theming properly in March when I have the time.
